name: swd8_intro_ml_test
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cuda=11.3
  - cudatoolkit=11.3
  - cudnn=8.2
  - jupyter-book
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.9
  - python-graphviz
  - pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
  - scikit-learn
  - torchvision
  - pip:
    - keras-tuner
    - lightning-bolts
    - lightning-flash
    - pytorch-lightning
    - ray
    - tensorboard
    - tensorflow
    - tensorflow-datasets
    - tensorflow-hub
    - torchmetrics
